#pragma once

// HTML du Web UI — stocké en flash (PROGMEM)
// Séparé du .ino pour éviter que Arduino IDE parse le JS comme du C++

const char HTML_PAGE[] PROGMEM =
"<!DOCTYPE html>"
"<html lang='fr'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>Lumière, Et le Buuut...</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;"
"background:#0f0f0f;color:#f0f0f0;min-height:100vh;display:flex;"
"flex-direction:column;align-items:center;justify-content:center;padding:24px}"
".card{background:#1a1a1a;border-radius:20px;padding:32px 28px;width:100%;"
"max-width:360px;box-shadow:0 8px 32px rgba(0,0,0,.5)}"
".logo{text-align:center;margin-bottom:28px}"
".logo svg{width:90px;height:90px}"
"h1{text-align:center;font-size:1.3rem;font-weight:700;color:#fff;margin-bottom:6px}"
".sub{text-align:center;font-size:.8rem;color:#666;margin-bottom:32px}"
".lbl{font-size:.72rem;text-transform:uppercase;letter-spacing:.1em;color:#555;margin-bottom:12px}"
".tog-row{display:flex;align-items:center;justify-content:space-between;"
"background:#242424;border-radius:14px;padding:16px 20px;margin-bottom:24px}"
".tog-label{font-size:1rem;font-weight:600}"
".sw{position:relative;width:52px;height:28px}"
".sw input{display:none}"
".sl{position:absolute;inset:0;background:#333;border-radius:28px;cursor:pointer;transition:background .25s}"
".sl::before{content:'';position:absolute;width:22px;height:22px;left:3px;top:3px;"
"background:#fff;border-radius:50%;transition:transform .25s}"
"input:checked+.sl{background:#af1e2d}"
"input:checked+.sl::before{transform:translateX(24px)}"
".cgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:28px}"
".cbtn{display:flex;flex-direction:column;align-items:center;gap:8px;"
"background:#242424;border:2px solid #333;border-radius:14px;padding:16px 8px;"
"cursor:pointer;transition:border-color .2s,background .2s}"
".cbtn.active{background:#1e1e1e}"
".cbtn.active.rouge{border-color:#e03040}"
".cbtn.active.blanc{border-color:#e0e0e0}"
".cbtn.active.bleu{border-color:#1a6bb5}"
".sw2{width:36px;height:36px;border-radius:50%;transition:box-shadow .2s}"
".rouge .sw2{background:#e03040}"
".blanc .sw2{background:#e8e8e8;border:1px solid #555}"
".bleu  .sw2{background:#1a6bb5}"
".cbtn.active.rouge .sw2{box-shadow:0 0 12px 4px #e03040}"
".cbtn.active.blanc .sw2{box-shadow:0 0 12px 4px #aaa}"
".cbtn.active.bleu  .sw2{box-shadow:0 0 12px 4px #1a6bb5}"
".cname{font-size:.82rem;font-weight:600;color:#ccc}"
".sbox{background:#242424;border-radius:14px;padding:14px 18px;font-size:.82rem;"
"color:#888;display:flex;justify-content:space-between;align-items:center}"
".dot{width:8px;height:8px;border-radius:50%;background:#444}"
".dot.live{background:#2ecc71;box-shadow:0 0 6px #2ecc71}"
".dot.goal{background:#e03040;box-shadow:0 0 6px #e03040;animation:p .5s infinite alternate}"
"@keyframes p{from{opacity:1}to{opacity:.3}}"
".led-row{display:flex;align-items:center;gap:10px;background:#242424;"
"border-radius:14px;padding:14px 18px;margin-bottom:16px}"
".led-row input[type=number]{background:#333;border:1px solid #444;border-radius:8px;"
"color:#fff;font-size:1rem;width:70px;padding:6px 10px;text-align:center}"
".led-row input[type=number]:focus{outline:none;border-color:#1a6bb5}"
".led-apply{background:#1a6bb5;color:#fff;border:none;border-radius:8px;"
"padding:8px 16px;font-size:.85rem;font-weight:600;cursor:pointer;transition:background .2s}"
".led-apply:active{background:#155a96}"
".led-ok{color:#2ecc71;font-size:.8rem;opacity:0;transition:opacity .3s}"
".bri-row{background:#242424;border-radius:14px;padding:14px 18px;margin-bottom:16px}"
".bri-row input[type=range]{width:100%;accent-color:#1a6bb5;margin:8px 0}"
".bri-labels{display:flex;justify-content:space-between;font-size:.72rem;color:#555}"
".log-btn{width:100%;background:#242424;color:#888;border:1px solid #333;"
"border-radius:14px;padding:12px;font-size:.85rem;font-weight:600;"
"cursor:pointer;margin-top:12px;transition:background .2s;text-align:left}"
".log-btn:hover{background:#2a2a2a}"
".log-panel{display:none;margin-top:8px;background:#111;border-radius:12px;"
"padding:12px;max-height:260px;overflow-y:auto}"
".log-panel pre{font-family:monospace;font-size:.72rem;color:#8f8;white-space:pre-wrap;"
"word-break:break-all;margin:0}"
".log-toolbar{display:flex;justify-content:space-between;align-items:center;"
"margin-bottom:8px}"
".log-toolbar span{font-size:.72rem;text-transform:uppercase;letter-spacing:.08em;color:#555}"
".log-clear{background:none;border:1px solid #333;border-radius:6px;color:#666;"
"font-size:.7rem;padding:3px 8px;cursor:pointer}"
".log-clear:hover{color:#e03040;border-color:#e03040}"
".footer{margin-top:20px;text-align:center}"
"</style></head>"
"<body>"
"<div class='card'>"
"<div class='logo'>"
"<svg viewBox='0 0 120 120' fill='none' xmlns='http://www.w3.org/2000/svg'>"
"<circle cx='60' cy='60' r='56' fill='#1a6bb5'/>"
"<circle cx='60' cy='60' r='56' fill='none' stroke='white' stroke-width='4'/>"
"<circle cx='60' cy='60' r='46' fill='none' stroke='white' stroke-width='1.5' stroke-dasharray='5 3.5'/>"
"<path id='arc' fill='none' d='M 18,60 A 42,42 0 0,1 102,60'/>"
"<text font-family='Arial,sans-serif' font-size='11' font-weight='700' fill='white' letter-spacing='3'>"
"<textPath href='#arc' startOffset='50%' text-anchor='middle'>POWERED BY</textPath>"
"</text>"
"<text x='60' y='78' text-anchor='middle' font-family='Georgia,serif' font-size='42' font-weight='bold' fill='white' letter-spacing='-2'>JQ</text>"
"</svg></div>"
"<h1>Lumière, Et le Buuut...</h1>"
"<p class='sub' id='ipLbl'>Chargement...</p>"
"<div class='lbl'>Lumiere</div>"
"<div class='tog-row'>"
"<span class='tog-label' id='pwrLbl'>ON</span>"
"<label class='sw'>"
"<input type='checkbox' id='togPwr' checked onchange='setPwr(this.checked)'>"
"<span class='sl'></span>"
"</label>"
"</div>"
"<div class='lbl'>Couleur entre les buts</div>"
"<div class='cgrid'>"
"<div class='cbtn rouge' id='bR' onclick='togCol(\"rouge\")'><div class='sw2'></div><span class='cname'>Rouge</span></div>"
"<div class='cbtn blanc' id='bW' onclick='togCol(\"blanc\")'><div class='sw2'></div><span class='cname'>Blanc</span></div>"
"<div class='cbtn bleu'  id='bB' onclick='togCol(\"bleu\")'> <div class='sw2'></div><span class='cname'>Bleu</span></div>"
"</div>"
"<div class='sbox'>"
"<span id='stTxt'>Chargement...</span>"
"<div class='dot' id='stDot'></div>"
"</div>"
"<br>"
"<div class='lbl'>Nombre de LEDs</div>"
"<div class='led-row'>"
"<input type='number' id='ledInput' min='1' max='300' value='28'>"
"<button class='led-apply' onclick='applyLeds()'>Appliquer</button>"
"<span class='led-ok' id='ledOk'>&#10003; Sauvegarde</span>"
"</div>"
"<div class='lbl' style='margin-top:16px'>Luminosite</div>"
"<div class='bri-row'>"
"<input type='range' id='briSlider' min='0' max='255' value='200' oninput='updateBri(this.value)' onchange='applyBri(this.value)'>"
"<div class='bri-labels'><span>0%</span><span id='briVal'>78%</span><span>100%</span></div>"
"</div>"
"<div style='display:flex;align-items:center;justify-content:space-between;"
"background:#242424;border-radius:14px;padding:14px 18px;margin-bottom:0'>"
"<div>"
"<div style='font-size:.85rem;font-weight:600'>Sauvegarder au redemarrage</div>"
"<div style='font-size:.72rem;color:#555;margin-top:2px'>Couleurs et ON/OFF persistent apres reboot</div>"
"</div>"
"<label class='sw'>"
"<input type='checkbox' id='togSave' onchange='setSaveColors(this.checked)'>"
"<span class='sl'></span>"
"</label>"
"</div>"
"<button class='log-btn' onclick='toggleLogs()' id='logBtn'>&#128203; Logs de l'appareil</button>"
"<div class='log-panel' id='logPanel'>"
"<div class='log-toolbar'>"
"<span>Activite en temps reel</span>"
"<button class='log-clear' onclick='clearLogs()'>Effacer</button>"
"</div>"
"<pre id='logText'>Chargement...</pre>"
"</div>"
"<a href='/update' style='display:block;margin-top:12px;background:#242424;color:#555;"
"border:1px solid #333;border-radius:14px;padding:12px;font-size:.85rem;font-weight:600;"
"text-align:left;text-decoration:none;transition:background .2s;'"
"onmouseover=\"this.style.background='#2a2a2a'\" onmouseout=\"this.style.background='#242424'\">"
"&#128640; Mise a jour firmware (OTA)</a>"
"<button onclick='reboot()' style='width:100%;margin-top:8px;background:#242424;color:#e03040;"
"border:1px solid #333;border-radius:14px;padding:12px;font-size:.85rem;font-weight:600;"
"cursor:pointer;text-align:left;transition:background .2s'"
"onmouseover=\"this.style.background='#2a2a2a'\" onmouseout=\"this.style.background='#242424'\">"
"&#128260; Redemarrer l'appareil</button>"
"</div>"
"<div class='footer'>"
"<svg viewBox='0 0 300 45' width='300' height='45' xmlns='http://www.w3.org/2000/svg'>"
"<text x='150' y='34' text-anchor='middle' font-family='Georgia,serif' font-size='30' font-weight='900' fill='#af1e2d' stroke='#002D62' stroke-width='4' paint-order='stroke'>Go Habs Go</text>"
"</svg>"
"</div>"
"<script>"
"function updSt(d){"
"var dot=document.getElementById('stDot'),"
"txt=document.getElementById('stTxt');"
"if(d.flashing){dot.className='dot goal';txt.textContent='BUT DES CANADIENS!';}"
"else if(d.gameActive){dot.className='dot live';txt.textContent='Match en cours - Score: '+d.score;}"
"else{dot.className='dot';txt.textContent='Aucune partie présentement';}"
"}"
"fetch('/state').then(function(r){return r.json();}).then(function(d){"
"document.getElementById('togPwr').checked=d.on;"
"document.getElementById('pwrLbl').textContent=d.on?'ON':'OFF';"
"document.getElementById('ipLbl').textContent='IP: '+d.ip;"
"document.getElementById('ledInput').value=d.ledCount||28;"
"document.getElementById('togSave').checked=d.saveColors||false;"
"var bri=d.brightness||200;"
"document.getElementById('briSlider').value=bri;"
"document.getElementById('briVal').textContent=Math.round(bri/255*100)+'%';"
"if(d.red)  document.getElementById('bR').classList.add('active');"
"if(d.white)document.getElementById('bW').classList.add('active');"
"if(d.blue) document.getElementById('bB').classList.add('active');"
"updSt(d);"
"});"
"setInterval(function(){"
"fetch('/state').then(function(r){return r.json();}).then(updSt);"
"},15000);"
"function setPwr(on){"
"document.getElementById('pwrLbl').textContent=on?'ON':'OFF';"
"fetch('/set?power='+(on?'1':'0'));"
"}"
"function setSaveColors(on){"
"fetch('/set?savecolors='+(on?'1':'0'));"
"}"
"function updateBri(v){"
"document.getElementById('briVal').textContent=Math.round(v/255*100)+'%';"
"}"
"function applyBri(v){"
"fetch('/brightness?val='+v);"
"}"
"function reboot(){"
"if(!confirm('Redemarrer l\\'appareil?'))return;"
"fetch('/reboot').then(function(){"
"setTimeout(function(){location.reload();},5000);"
"});"
"}"
"function togCol(c){"
"var id=c==='rouge'?'bR':c==='blanc'?'bW':'bB';"
"var btn=document.getElementById(id);"
"var a=btn.classList.toggle('active');"
"fetch('/set?color='+c+'&val='+(a?'1':'0'));"
"}"
"function applyLeds(){"
"var n=parseInt(document.getElementById('ledInput').value);"
"if(isNaN(n)||n<1||n>300){alert('Valeur entre 1 et 300');return;}"
"fetch('/setleds?count='+n).then(function(r){"
"if(r.ok){"
"var ok=document.getElementById('ledOk');"
"ok.style.opacity='1';"
"setTimeout(function(){ok.style.opacity='0';},2000);"
"}"
"});"
"}"
"var logOpen=false,logTimer=null;"
"function toggleLogs(){"
"logOpen=!logOpen;"
"var p=document.getElementById('logPanel');"
"var b=document.getElementById('logBtn');"
"if(logOpen){"
"p.style.display='block';"
"b.textContent='\\u25B2 Fermer les logs';"
"fetchLogs();"
"logTimer=setInterval(fetchLogs,3000);"
"}else{"
"p.style.display='none';"
"b.innerHTML='\\u{1F4CB} Logs de l\\'appareil';"
"clearInterval(logTimer);"
"}"
"}"
"function fetchLogs(){"
"fetch('/logs').then(function(r){return r.text();}).then(function(t){"
"var el=document.getElementById('logText');"
"el.textContent=t||'(aucun log)';"
"var p=document.getElementById('logPanel');"
"p.scrollTop=p.scrollHeight;"
"});"
"}"
"function clearLogs(){"
"document.getElementById('logText').textContent='(logs effaces localement)';"
"}"
"</script>"
"</body></html>";
